### ISSUE TITLE
Maybe non-issue: exploration always finishes quick

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/IDeSyDe#36]
Regardless of which input problem (tc1-tc4) the exploration takes just a few seconds and I wonder if there is some mistake or if the design space is so small that searching it exhaustively is super fast simply

**Comment by Rojods** [comment]
The design spaces are indeed small @BeethovenKodar ! Because of the discretization that happens when `AperiodicAsynchronousDataflowToPartitionedMemoryMappableMulticoreAndPL` goes to a CP solver, the design space is actually very small for these cases, GIVEN the actual mathematical model that we have :).
